on: [push, pull_request]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [".", "./integration"]
        go: [ "1.25.x", "1.26.x" ]
    name: Lint (${{ matrix.module }}, Go ${{ matrix.go }})
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Check for //go:build ignore in .go files
        working-directory: ${{ matrix.module }}
        run: |
          IGNORED_FILES=$(grep -rl '//go:build ignore' . --include='*.go') || true
          if [ -n "$IGNORED_FILES" ]; then
            echo "::error::Found ignored Go files: $IGNORED_FILES"
            exit 1
          fi
      - name: Check that go.mod is tidied
        if: success() || failure() # run this step even if the previous one failed
        working-directory: ${{ matrix.module }}
        run: go mod tidy -diff
      - name: Run go fix
        if: (success() || failure()) && matrix.go == '1.26.x'
        working-directory: ${{ matrix.module }}
        run: go fix -diff ./...
      - name: gofmt
        if: success() || failure() # run this step even if the previous one failed
        working-directory: ${{ matrix.module }}
        run: |
          out=$(gofmt -s -l .)
          if [[ -n "$out" ]]; then
            echo $out | awk '{print "::error file=" $0 ",line=0,col=0::File is not gofmt-ed."}'
            exit 1
          fi
      - name: go vet
        if: success() || failure() # run this step even if the previous one failed
        working-directory: ${{ matrix.module }}
        run: go vet ./...
      - name: Install staticcheck
        if: success() || failure() # run this step even if the previous one failed
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.7.0
      - name: staticcheck
        if: success() || failure() # run this step even if the previous one failed
        working-directory: ${{ matrix.module }}
        run: |
          set -o pipefail
          staticcheck ./... | sed -e 's@\(.*\)\.go@./\1.go@g'
